### PR TITLE
Window controls overlay

### PR DESCRIPTION
**Pull request by s1gnate-sync**
Based on this article: https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay

Some minor eye-candy.

Screenshot 2024-04-02 15 39 16

### CODE REVIEW

**Comment by s1gnate-sync** [comment]
to make it even better it would be great if silverbullet can match os theme, it should be relatively easy to detect using

```
@media (prefers-color-scheme: dark) {
  :root {
    /* Dark mode variables go here */
  }
}
```

**Comment by s1gnate-sync** [comment]
There is a room for improvement, but in require a bit more changes so I decided to split it in two. Since we have `titlebar-area-height` we can also make navigation bar and icons smaller so they would be the same height as native window decoration.

**Comment by zefhemel** [comment]
Interesting. I’ll give this a try later. It looks a bit odd in your screenshot, but maybe I’m just not used to the Windows aesthetic.

**Comment by s1gnate-sync** [comment]
@zefhemel it's chromeos :-)

**Comment by zefhemel** [comment]
I don't have chromeos so I can't test it there, but this doesn't seem to break anything in Safari nor Chome. So I'll merge this. Thanks!

**Pull request merged**
