### PR TITLE
adjust directive header's height when cursor is outside

### PR DESCRIPTION
**Pull request by vuau**
The directive is taking up so much precious space in mobile view.

Screenshot from 2023-07-01 16-08-36

It should be smaller when the cursor is outside of the directive
Screenshot from 2023-07-01 16-27-11

And become bigger when the cursor is inside the directive
Screenshot from 2023-07-01 16-18-26

### CODE REVIEW

**Comment by zefhemel** [comment]
I think this is the same as #425 see why I did this here: https://github.com/silverbulletmd/silverbullet/issues/208

**Comment by vuau** [comment]
> I think this is the same as #425 see why I did this here: https://github.com/silverbulletmd/silverbullet/issues/208

Yes same. Have you merged those improvements to the main branch? I checkout it yesterday and the issue still remain

**Comment by zefhemel** [comment]
The issue explains why I introduced this "problem" and why.

**Comment by vuau** [comment]
So sorry I misread your point. My fix is just about reducing the vertical space and it doesn't cause the cursor jump as in my test

https://github.com/silverbulletmd/silverbullet/assets/259848/1617ed6d-235a-4c8c-8526-aa68e582ac7e

**Comment by zefhemel** [comment]
This is indeed less of an issue on mobile, where you don't usually "walk" the cursor down (via the keyboard) but you just tap places. The vertical jump happens then (as you can also see in the video) but it's less of an issue, so maybe a compromise would be to do fold this vertically _just_ on mobile? An argument could also be the more limited screen real estate.

For this I/somebody would need to add a "on mobile" type CSS selector on the body tag maybe to make this distiction.

**Comment by vuau** [comment]
Yeah. I think I can make that CSS if you don't have time to work on it. Do we have a JS function somewhere to check if SB is on mobile or can I just use CSS media-query?

**Comment by zefhemel** [comment]
There's no function for this right now I don't think. A media query could indeed work, for certain size screens?

**Pull request closed without merging**
