### PR TITLE
Widget buttons for transclusions (#942)

### PR DESCRIPTION
**Pull request by onespaceman**

### CODE REVIEW

**Comment by zefhemel** [comment]
Stream of consciousness ahead:

What I had in mind the Edit button would do is navigate to the transcluded page. However, now that I'm thinking about it this is somewhat inconsistent with the general Edit button meaning on widgets, which usually indeed puts the cursor inside the body to allow you to edit the source (query, template).

Now the question is: what is the "source" in this case, the link itself, or the page it links to? 

In practice what I would want to do when pushing this edit button is edit the underlying page (that is transcluded) so I'd still prefer the navigate option. Do you agree?

**Comment by onespaceman** [comment]
Sounds reasonable. I could also change the icon to a link and hover text to "Open page" so there's no ambiguity.

**Comment by zefhemel** [comment]
Sounds good

**Comment by zefhemel** [comment]
Ready to look at again?

**Comment by onespaceman** [comment]
yes

**Comment by zefhemel** [comment]
Works great, thanks!

**Pull request merged**
