### PR TITLE
WIP: Theming changes

### PR DESCRIPTION
**Pull request by simcard0000**
Right now, this is a very rough and incomplete draft, wherein the work will be split into two parts:

- [ ] refactoring SCSS code relating to theming
- [ ] overhauling the built-in dark theme and making some improvements to the light theme

Feedback is appreciated! Also, see [Theming support #10](https://github.com/silverbulletmd/silverbullet/issues/10), [Theming approach #58](https://github.com/silverbulletmd/silverbullet/discussions/58), and [Improve dark mode #127](https://github.com/silverbulletmd/silverbullet/issues/127).

### CODE REVIEW

**Comment by zefhemel** [comment]
My current thinking (but I’m open to alternative ideas) is to distribute themes as plugs. If we do this, there’s a good argument to allow theming in pure CSS without having to preprocess them with e.g. SCSS, do you think that’s doable or would be too verbose? We can probably include a SCSS preprocessing step somewhere if necessary.

**Comment by simcard0000** [comment]
@zefhemel It's a neat idea; and fits in with the overall ethos of "plugs all the way down". I'm not 100% sure if it'll be too verbose, but if themes are plugs then it makes it easy to enable/disable custom themes (which I guess is for now adding/removing plugs from the PLUGS page or through plug management). 

I think it's still the right track to have a `theme.scss` file where we can put any properties/parts that can be "safely changed"; and have it wrapped up in a CSS `@layer` rule, which means that any styles declared outside of this will override the styles declared in the layer, regardless of specificity. That way people can worry less about the structure of their CSS in their plugs.

**Comment by zefhemel** [comment]
Alright, let me know when I should have a closer look. I'm no SCSS expert by any means, so I'll largely trust your judgment :)

**Comment by simcard0000** [comment]
@zefhemel To be fair I'm no SCSS expert either 😅 but it's fun figuring out how to design a theming system 🙂

**Comment by zefhemel** [comment]
Closing this due to staleness.

**Pull request closed without merging**
