### PR TITLE
Include a preview of another note

### PR DESCRIPTION
**Pull request by stellarorion**
I think that this could be a useful default template for people to include previews of other (markdown files). Such as is done in the intro/tutorial (Getting started) file.

### CODE REVIEW

**Comment by zefhemel** [comment]
Looks good to me, except for the terminology. I try to consistently use the term "page" instead of "note", so if you can change that I'm happy to merge.

**Comment by stellarorion** [comment]
Great! I will do the change later today and let you know 😄.

**Comment by stellarorion** [comment]
Done, and I just realized that GitHub actually posts the changes in the thread, LOL.

**Comment by zefhemel** [comment]
Thanks!

**Pull request merged**
