### PR TITLE
Object decorators

### PR DESCRIPTION
**Pull request by zefhemel**
To replace the `pageDecoration` with something more generic and powerful.

cc @onespaceman

### CODE REVIEW

**Comment by onespaceman** [comment]
This looks good!

I'll rebase #945 to this branch.
Also I think you're right about just attaching a class through decorator, instead of data-attributes to the html. It should make the snippets much cleaner.

**Comment by onespaceman** [comment]
A request: Could you make arrays be merged instead of overwritten when eriching metadata. useful for applying multiple classes/tags to a page

**Comment by onespaceman** [comment]
Also, all attributes (dates, ref, name etc.) can be overwritten with the decorator.

**Comment by zefhemel** [comment]
Ok, both should now be there.

**Pull request merged**
